'use strict';
// app.js — ChoctoTV main application
// Twitch chat + game engine + balance/items + WebSocket + overlay HTTP + REST API
// All in one process — no inter-service HTTP calls, no race conditions

const fs      = require('fs');
const path    = require('path');
const crypto  = require('crypto');
const os      = require('os');
const express = require('express');
const { WebSocketServer } = require('ws');
const tmi     = require('tmi.js');

require('dotenv').config();
// ── Crypto: derives AES key by scattering STREAM_KEY + CLIENT_ID bits ────────
// Both keys are required. Key derivation interleaves bytes from each at
// positions driven by the other key's char codes, then folds + PBKDF2.
// Without SECRET.txt (which holds both keys) the .env is unreadable.
(function decryptEnv() {
  // Reads ~/.choctotv.key (saved by setup.js) — app never needs SECRET.txt at runtime
  const fs     = require('fs');
  const path   = require('path');
  const crypto = require('crypto');
  const os     = require('os');
  const PREFIX = 'enc:';
  const SALT   = 'ChoctoTV-v2';

  function tryDecrypt(key) {
    let n = 0;
    for (const [k, v] of Object.entries(process.env)) {
      if (!v || !v.startsWith(PREFIX)) continue;
      try {
        const buf = Buffer.from(v.slice(PREFIX.length), 'base64');
        const d   = crypto.createDecipheriv('aes-256-gcm', key, buf.slice(0,12));
        d.setAuthTag(buf.slice(12,28));
        process.env[k] = Buffer.concat([d.update(buf.slice(28)), d.final()]).toString('utf8');
        n++;
      } catch(e) { console.error(`[crypto] Cannot decrypt ${k}`); }
    }
    return n;
  }

  // Primary: ~/.choctotv.key (generated by setup.js)
  const keyFile = path.join(os.homedir(), '.choctotv.key');
  if (fs.existsSync(keyFile)) {
    try {
      const key = Buffer.from(fs.readFileSync(keyFile, 'utf8').trim(), 'hex');
      const n   = tryDecrypt(key);
      if (n > 0) { console.log(`[crypto] ${n} values decrypted via ~/.choctotv.key`); return; }
    } catch(e) { console.warn('[crypto] keyfile error:', e.message); }
  }

  // Fallback: derive key from SECRET.txt
  const secretFile = path.join(__dirname, 'SECRET.txt');
  if (!fs.existsSync(secretFile)) {
    console.warn('[crypto] No ~/.choctotv.key and no SECRET.txt — run: node setup.js');
    return;
  }
  const S = {};
  for (const line of fs.readFileSync(secretFile, 'utf8').split('\n')) {
    const clean = line.split('#')[0].trim();
    const eq = clean.indexOf('=');
    if (eq < 0) continue;
    const k = clean.slice(0, eq).trim().toUpperCase();
    const v = clean.slice(eq + 1).trim();
    if (k && v && !k.startsWith('\u2550')) S[k] = v;
  }
  const sk = S['STREAM_KEY'] || '', ci = S['CLIENT_ID'] || '';
  if (!sk || !ci) { console.warn('[crypto] SECRET.txt missing STREAM_KEY or CLIENT_ID'); return; }
  console.warn('[crypto] Using SECRET.txt fallback — run: node setup.js to generate ~/.choctotv.key');

  function deriveKey(sk_, ci_) {
    const skb = Buffer.from(sk_,'utf8'), cib = Buffer.from(ci_,'utf8');
    const ml = Math.max(skb.length,cib.length)*2+16;
    const mx = Buffer.alloc(ml,0);
    let si=0,ci_i=0,mi=0;
    while(si<skb.length||ci_i<cib.length){
      if(si<skb.length){mx[mi%ml]^=skb[si];const s=ci_i<cib.length?(cib[ci_i%cib.length]%3)+1:1;mi+=s;si++;}
      if(ci_i<cib.length){mx[mi%ml]^=cib[ci_i];const s=si<skb.length?(skb[si%skb.length]%3)+1:1;mi+=s;ci_i++;}
    }
    const rev=Buffer.from(ci_.split('').reverse().join(''));
    for(let i=0;i<ml;i++){mx[i]^=rev[i%rev.length];mx[i]^=skb[(i*7+3)%skb.length];}
    const h=Math.floor(ml/2),sd=Buffer.alloc(h);
    for(let i=0;i<h;i++)sd[i]=mx[i]^mx[i+h]^(i&0xff);
    return crypto.pbkdf2Sync(sd,SALT,100000,32,'sha256');
  }
  tryDecrypt(deriveKey(sk, ci));
})();


// ── Config from env ───────────────────────────────────────────────────────────
const CHANNEL    = (process.env.TWITCH_CHANNEL      || '').toLowerCase();
const BOT_NAME   = (process.env.TWITCH_BOT_USERNAME || CHANNEL).toLowerCase();
const OAUTH_TOKEN= process.env.TWITCH_OAUTH_TOKEN   || '';
const CLIENT_ID  = process.env.TWITCH_CLIENT_ID     || '';
const RTMP_BASE  = process.env.TWITCH_RTMP_BASE     || 'rtmp://live.twitch.tv/app';
const API_PORT   = parseInt(process.env.API_PORT     || '3000');
const WS_PORT    = parseInt(process.env.WS_PORT      || '3001');
const OVL_PORT   = parseInt(process.env.OVERLAY_PORT || '8080');
const OVL_DIR    = path.join(__dirname, 'yardpets3');
const DATA_DIR   = path.join(__dirname, 'data');

if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive:true });

// ── Persist helper ────────────────────────────────────────────────────────────
function makePersist(file, defaultVal) {
  let data    = defaultVal;
  let timer   = null;
  const full  = path.join(DATA_DIR, file);
  try { data = { ...defaultVal, ...JSON.parse(fs.readFileSync(full, 'utf8')) }; } catch {}
  const save = () => {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => {
      try { fs.writeFileSync(full, JSON.stringify(data, null, 2)); } catch(e) { console.error(`[persist] ${file}:`, e.message); }
    }, 500);
  };
  return { data, save, get: k => data[k], set: (k, v) => { data[k] = v; save(); } };
}

// ── Data stores ───────────────────────────────────────────────────────────────
const balanceStore = makePersist('balances.json', {});
const itemsStore   = makePersist('items.json',    {});
const rolesStore   = makePersist('roles.json',    { mods:[], devs:[], pending:[] });
const coinsStore   = makePersist('coins.json',    {});
const gauntletStore = makePersist('gauntlet.json', { leaderboard:{}, dailyUsed:{} });
const gauntlet_canRun = u => {
  const d = gauntletStore.data.dailyUsed || {};
  return d[u] !== new Date().toISOString().slice(0,10);
};
const gauntlet_markUsed = u => {
  if (!gauntletStore.data.dailyUsed) gauntletStore.data.dailyUsed = {};
  gauntletStore.data.dailyUsed[u] = new Date().toISOString().slice(0,10);
  gauntletStore.save();
};
const gauntlet_record = (u, wins, total) => {
  const lb = gauntletStore.data.leaderboard || {};
  const prev = lb[u] || { wins:0, runs:0 };
  lb[u] = { wins:Math.max(prev.wins, wins), runs:(prev.runs||0)+1, lastRun:new Date().toISOString().slice(0,10), total };
  gauntletStore.data.leaderboard = lb;
  gauntletStore.save();
  return lb[u];
};
const gauntlet_leaderboard = () => {
  const lb = gauntletStore.data.leaderboard || {};
  return Object.entries(lb)
    .map(([u,d]) => ({ user:u, ...d }))
    .sort((a,b) => b.wins - a.wins)
    .slice(0, 20);
};
const lotteryStore = makePersist('lottery.json',  { tickets:{}, lastDraw:null });

// ── Live config ───────────────────────────────────────────────────────────────
const CONFIG_DEFAULTS = {
  toss_min:3,         toss_max:7,
  throw_min:3,        throw_max:7,
  dig_min:3,          dig_max:7,
  walk_min:2,         walk_max:5,
  fish_min:3,         fish_max:8,
  sticks_min:3,       sticks_max:5,
  balls_min:1,        balls_max:3,
  moon_chance:0.05,
  cooldown_ms:8000,   sub_cooldown_ms:4000,
  vend_sticks_rate:1, vend_balls_rate:50, vend_moons_rate:200,
  forge_balls_cost:100, forge_moons_cost:100,
  vend_min:100,       vend_max:999,
  reward_multiplier:1.0, earn_target_hr:25000, active_window_min:10,
  autopilot_sec:45,   weather_min_ms:900000,
  lurk_duration_hr:8, lurk_reward_mult:0.33,
  chest_min_lock:50,  chest_max_lock:500,
  gbm_round_min:10,   gbm_win_reward:0, gbm_tie_reward:1,
  music_volume:50,    music_enabled:1,
  mod_onduty_boost:0.10,
  airdrop_min:1000,   airdrop_max:25000,
  airdrop_mod_budget:5000, airdrop_dev_budget:25000,
  airdrop_window_min:60,
};
let _cfg = { ...CONFIG_DEFAULTS };
try { _cfg = { ...CONFIG_DEFAULTS, ...JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'config.json'), 'utf8')) }; } catch {}
const C = {
  get: k => _cfg[k] ?? CONFIG_DEFAULTS[k] ?? null,
  set: (k, v) => {
    if (!(k in CONFIG_DEFAULTS)) return { ok:false, error:`Unknown setting: "${k}"` };
    const num = parseFloat(v);
    if (isNaN(num)) return { ok:false, error:`${k} must be a number` };
    const old = _cfg[k]; _cfg[k] = num;
    try { fs.writeFileSync(path.join(DATA_DIR, 'config.json'), JSON.stringify(_cfg, null, 2)); } catch {}
    return { ok:true, key:k, value:num, prev:old };
  },
  all: () => ({ ..._cfg }),
};

// ── Balance / Items helpers ───────────────────────────────────────────────────
const getBalance  = u => balanceStore.data[u] || 0;
const addBalance  = (u, n) => { balanceStore.data[u] = Math.round(((balanceStore.data[u]||0) + n) * 100) / 100; balanceStore.save(); };
const subBalance  = (u, n) => { balanceStore.data[u] = Math.max(0, (balanceStore.data[u]||0) - n); balanceStore.save(); };
const zeroBalance = u => { balanceStore.data[u] = 0; balanceStore.save(); };
const getItems    = u => itemsStore.data[u] || { sticks:0, balls:0, moons:0 };
const addItems    = (u, d) => { const i = getItems(u); Object.keys(d).forEach(k => i[k] = Math.floor((i[k]||0) + (d[k]||0))); itemsStore.data[u] = i; itemsStore.save(); };
const spendItems  = (u, d) => {
  const i = getItems(u);
  for (const [k, n] of Object.entries(d)) { if ((i[k]||0) < n) return { ok:false, error:`Not enough ${k}` }; }
  for (const [k, n] of Object.entries(d)) i[k] = (i[k]||0) - n;
  itemsStore.data[u] = i; itemsStore.save(); return { ok:true };
};

// ── Coins (price ticker) ──────────────────────────────────────────────────────
const CONTRACT = process.env.CHOCTOPUS_CONTRACT || 'EVrGfAj99Xr1NjqqZv6E2msVKZVmhGaThHhcZXzrpump';
if (!coinsStore.data.coins) {
  coinsStore.data.coins = [
    { sym:'SOL',   id:'solana',   color:'#9945ff' },
    { sym:'CHOCT', id:CONTRACT,   color:'#b060ff' },
  ];
  coinsStore.save();
}
const getCoins    = () => coinsStore.data.coins || [];
const addCoin     = (sym, id) => { if (!sym||!id) return { ok:false, error:'sym and id required' }; const coins=getCoins(); if(coins.find(c=>c.sym.toUpperCase()===sym.toUpperCase())) return {ok:false,error:`${sym} already in ticker`}; coins.push({sym:sym.toUpperCase(),id,color:'#ffffff'}); coinsStore.data.coins=coins; coinsStore.save(); return {ok:true,coin:{sym:sym.toUpperCase(),id}}; };
const removeCoin  = sym => { const coins=getCoins(); const i=coins.findIndex(c=>c.sym.toUpperCase()===sym.toUpperCase()); if(i<0) return {ok:false,error:`${sym} not found`}; const [removed]=coins.splice(i,1); coinsStore.data.coins=coins; coinsStore.save(); return {ok:true,sym:removed.sym}; };

// ── Sprites ───────────────────────────────────────────────────────────────────
let _sprites = [];
try {
  const raw = JSON.parse(fs.readFileSync(path.join(OVL_DIR, 'assets', 'sprites_meta.json'), 'utf8'));
  if (Array.isArray(raw)) raw.forEach(o => { if (Array.isArray(o.sprites)) _sprites.push(...o.sprites); else if (o.name) _sprites.push(o); });
  else if (raw.sprites) _sprites = raw.sprites;
  console.log(`[Sprites] ${_sprites.length} pups loaded`);
} catch(e) { console.warn('[Sprites] Could not load sprites_meta.json:', e.message); }

const getPupName   = id => _sprites[Math.abs(parseInt(id)||0) % Math.max(1,_sprites.length)]?.name || null;
const getPupRarity = id => (_sprites[Math.abs(parseInt(id)||0) % Math.max(1,_sprites.length)]?.rarity || 'common').toLowerCase();
const assignPup    = () => _sprites.length ? Math.floor(Math.random() * _sprites.length) : Math.floor(Math.random() * 1e6);

// Pick a caught pup for fishing — must be different from companion, same rarity or lower
const catchPup = (companionId, companionRarity) => {
  if (!_sprites.length) return null;
  const rarityOrder = ['common','uncommon','rare','epic','legendary'];
  const maxIdx      = rarityOrder.indexOf((companionRarity||'common').toLowerCase());
  const eligible    = _sprites
    .map((s, i) => ({ ...s, i }))
    .filter(s => {
      const ri = rarityOrder.indexOf((s.rarity||'common').toLowerCase());
      return s.i !== companionId && ri <= maxIdx; // different pup, same rarity or lower
    });
  if (!eligible.length) return null;
  const caught = eligible[Math.floor(Math.random() * eligible.length)];
  return { catchId: caught.i, catchName: caught.name, catchRarity: (caught.rarity||'common').toLowerCase() };
};

// ── Weather ───────────────────────────────────────────────────────────────────
let weather = 'sunny';
const WEATHERS = ['sunny','cloudy','rainy','stormy','snowy','windy'];
const W_ICONS  = { sunny:'☀️', cloudy:'☁️', rainy:'🌧️', stormy:'⛈️', snowy:'❄️', windy:'💨' };

// ── Pup daily favourites ──────────────────────────────────────────────────────
const FAV_GAMES = ['toss','throw','dig','walk','fish'];
function djb2(s) { let h=5381; for(let i=0;i<s.length;i++) h=((h<<5)+h)+s.charCodeAt(i); return Math.abs(h); }
const today = () => new Date().toISOString().slice(0,10);
const getDailyFav = (name, list, shift=0) => {
  if (!name) return null;
  const d = today(), prev = new Date(Date.now()-86400000).toISOString().slice(0,10);
  const ti = djb2(name+d+shift) % list.length;
  const pi = djb2(name+prev+shift) % list.length;
  return list[ti === pi ? (ti+1) % list.length : ti];
};
const getPupBonus = (name, game) => {
  if (!name) return { mult:1, bonuses:[] };
  const fg = getDailyFav(name, FAV_GAMES, 0);
  const fw = getDailyFav(name, WEATHERS, 7);
  let bonus = 0; const bonuses = [];
  if (game === fg)     { bonus += C.get('mod_onduty_boost'); bonuses.push('game'); }
  if (weather === fw)  { bonus += 0.10; bonuses.push('weather'); }
  return { mult:1+bonus, favGame:fg, favWeather:fw, bonuses };
};

// ── Reward calc ───────────────────────────────────────────────────────────────
const RARITIES = ['common','uncommon','rare','epic','legendary'];
const RAR_W    = [50,25,15,7,3];
const ICONS    = { sticks:'🪵', balls:'🎾', moons:'🌙', chocto:'🍫' };
const fmtN     = n => { const v = n||0; return Number.isInteger(v) ? v.toLocaleString('en-US') : v.toLocaleString('en-US',{minimumFractionDigits:1,maximumFractionDigits:2}); };
const activeUsers = new Map();
const markActive  = u => activeUsers.set(u.toLowerCase(), Date.now());
const getActiveCount = () => {
  const win = C.get('active_window_min') * 60000, now = Date.now(); let n = 0;
  for (const [u,ts] of activeUsers) { if (now-ts < win) n++; else activeUsers.delete(u); }
  return Math.max(1, n);
};
const randomRarity = () => { let r = Math.random()*RAR_W.reduce((s,w)=>s+w,0); for(let i=0;i<RAR_W.length;i++){r-=RAR_W[i];if(r<=0)return RARITIES[i];}return 'common'; };
const rollDrops = () => {
  const d = {};
  const sm = C.get('sticks_min'), sx = C.get('sticks_max');
  const bm = C.get('balls_min'),  bx = C.get('balls_max');
  if (sx > 0) d.sticks = Math.floor(Math.random()*(sx-sm+1))+sm;
  if (bx > 0) d.balls  = Math.floor(Math.random()*(bx-bm+1))+bm;
  if (Math.random() < C.get('moon_chance')) d.moons = 1;
  return d;
};
const calcReward = game => {
  const mn = C.get(`${game}_min`) || 3, mx = C.get(`${game}_max`) || 7;
  const base = Math.floor(Math.random()*(mx-mn+1))+mn;
  const cd   = (C.get('cooldown_ms')||8000)/1000;
  const cal  = (C.get('earn_target_hr')||25000) / (5.15 * (60/cd) * 60);
  const ps   = Math.max(1, getActiveCount() / Math.max(1, (C.get('earn_target_hr')||25000)/24.7/(60/cd)));
  return Math.round(base * cal * ps * (C.get('reward_multiplier')||1));
};

// ── Cooldowns ─────────────────────────────────────────────────────────────────
const cooldowns = new Map();
const onCooldown = (user, isMod, isSub) => {
  if (isMod) return false;
  const cd = isSub ? C.get('sub_cooldown_ms') : C.get('cooldown_ms');
  const now = Date.now();
  if (now - (cooldowns.get(user)||0) < cd) return true;
  cooldowns.set(user, now);
  return false;
};
const lastCmd = new Map();
const isRepeat = (u, cmd) => { if(lastCmd.get(u)===cmd) return true; lastCmd.set(u,cmd); return false; };

// ── .env writer ───────────────────────────────────────────────────────────────
const ENV_FILE = path.join(__dirname, '.env');
const writeEnvKey = (key, val) => {
  try {
    let s = fs.readFileSync(ENV_FILE, 'utf8');
    const re = new RegExp(`^${key}=.*$`,'m');
    s = re.test(s) ? s.replace(re, `${key}=${val}`) : s + `\n${key}=${val}`;
    fs.writeFileSync(ENV_FILE, s);
    return true;
  } catch { return false; }
};

// ═══════════════════════════════════════════════════════════════════════════════
// INLINED: LURK MANAGER
// ═══════════════════════════════════════════════════════════════════════════════
const lurkMap = new Map();
const lurk_add = u => {
  const ms = C.get('lurk_duration_hr') * 3600000;
  if (lurkMap.has(u)) { const i=lurkMap.get(u); i.until=Date.now()+ms; i.seen=Date.now(); return { ok:true, existing:true }; }
  const info = { until:Date.now()+ms, seen:Date.now(), timer:null };
  const tick = () => {
    if (!lurkMap.has(u) || Date.now() > lurkMap.get(u).until) return;
    handleCommand('lurk_tick', u, [], true).catch(()=>{});
    info.timer = setTimeout(tick, C.get('cooldown_ms'));
  };
  info.timer = setTimeout(tick, 500);
  lurkMap.set(u, info); return { ok:true, existing:false };
};
const lurk_remove = u => { const i=lurkMap.get(u); if(!i) return false; clearTimeout(i.timer); lurkMap.delete(u); return true; };
const lurk_touch  = u => { const i=lurkMap.get(u); if(i) i.seen=Date.now(); };
const lurk_active = u => lurkMap.has(u);
setInterval(() => {
  const now = Date.now();
  for (const [u, info] of lurkMap) {
    if (now > info.until) { lurk_remove(u); say(`👋 @${u} lurk session expired.`); }
  }
}, 10 * 60000);

// ═══════════════════════════════════════════════════════════════════════════════
// INLINED: CHEST GAME
// ═══════════════════════════════════════════════════════════════════════════════
let chestLock = 0, chestLickers = new Map();
const chest_new = () => {
  const mn = C.get('chest_min_lock'), mx = C.get('chest_max_lock');
  chestLock = Math.floor(Math.random()*(mx-mn+1))+mn;
  chestLickers = new Map();
  broadcast({ type:'chest_new', lock:chestLock });
  console.log(`[Chest] New lock: ${chestLock}`);
};
const chest_lick = async u => {
  if (chestLock <= 0) chest_new();
  const clicks = Math.min(Math.floor(Math.random()*3)+1, chestLock);
  chestLock -= clicks;
  chestLickers.set(u, (chestLickers.get(u)||0) + clicks);
  broadcast({ type:'chest_lick', user:u, clicks, lock:chestLock });
  if (chestLock <= 0) {
    for (const [cu, cc] of chestLickers) addBalance(cu, cc);
    const top = [...chestLickers.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5);
    say(`🔓 Chest unlocked! ${top.map(([cu,cc])=>`@${cu}+${cc}`).join(' ')} 🍫`);
    broadcast({ type:'chest_pop', top });
    setTimeout(chest_new, 1000);
    return { ok:true, popped:true };
  }
  return { ok:true, clicks, lock:chestLock, popped:false };
};

// ═══════════════════════════════════════════════════════════════════════════════
// INLINED: GBM GAME
// ═══════════════════════════════════════════════════════════════════════════════
const GBM_BEATS = { Good:'Moon', Moon:'Ball', Ball:'Good' };
const GBM_PICKS = ['Good','Ball','Moon'];
const gbmPicks  = new Map();
let gbmTimer = null, gbmNext = 0;
const gbm_schedule = () => {
  if (gbmTimer) clearTimeout(gbmTimer);
  const ms = C.get('gbm_round_min') * 60000;
  gbmNext  = Date.now() + ms;
  gbmTimer = setTimeout(gbm_run, ms);
};
const gbm_pick = (u, raw) => {
  const p = GBM_PICKS.find(x => x.toLowerCase() === raw.toLowerCase() || x[0].toLowerCase() === raw[0]?.toLowerCase());
  if (!p) return { ok:false, error:`Invalid — choose Good, Ball, or Moon` };
  gbmPicks.set(u, p); return { ok:true, pick:p };
};
const gbm_run = async () => {
  if (!gbmPicks.size) { say(`🎮 GoodBallMoon — no picks this round! Use !GBM Good/Ball/Moon`); gbm_schedule(); return; }
  const winner = GBM_PICKS[Math.floor(Math.random()*3)];
  const beats  = GBM_BEATS[winner];
  const winR   = C.get('gbm_win_reward') || Math.max(1, getActiveCount());
  const tieR   = C.get('gbm_tie_reward') || 1;
  const W=[], T=[], L=[];
  for (const [u, p] of gbmPicks) {
    if (p === winner) { W.push(u); addBalance(u, winR); }
    else if (p === beats) L.push(u);
    else { T.push(u); if (tieR > 0) addBalance(u, tieR); }
  }
  gbmPicks.clear();
  say(`🎮 GBM: ${winner} wins! 🏆${W.length}+${fmtN(winR)}🍫 🤝${T.length}+${fmtN(tieR)}🍫 💀${L.length}`);
  broadcast({ type:'gbm_result', winner, winners:W, ties:T, losers:L, winR, tieR });
  gbm_schedule();
};

// ═══════════════════════════════════════════════════════════════════════════════
// INLINED: ROLES
// ═══════════════════════════════════════════════════════════════════════════════
const PEND_TTL = 7 * 86400000;
const modsOnDuty = new Set(), devsOnDuty = new Set();
const budgets    = new Map();
const roles      = rolesStore.data;
if (!roles.mods)    roles.mods    = [];
if (!roles.devs)    roles.devs    = [];
if (!roles.pending) roles.pending = [];

const roles_save   = () => rolesStore.save();
const isMod  = u => roles.mods.includes(u) || roles.pending.some(p=>p.u===u&&Date.now()<p.exp);
const isDev  = u => roles.devs.includes(u);
const canDrop= u => isMod(u)||isDev(u);
const addMod = u => { roles.pending=roles.pending.filter(p=>p.u!==u); if(!roles.mods.includes(u))roles.mods.push(u); roles_save(); };
const remMod = u => { roles.mods=roles.mods.filter(m=>m!==u); roles.pending=roles.pending.filter(p=>p.u!==u); modsOnDuty.delete(u); roles_save(); };
const addDev = u => { if(!roles.devs.includes(u))roles.devs.push(u); roles_save(); };
const remDev = u => { roles.devs=roles.devs.filter(d=>d!==u); devsOnDuty.delete(u); roles_save(); };
const addPending = (u, by) => {
  if (roles.mods.includes(u)) return { ok:false, r:'confirmed' };
  const ex = roles.pending.find(p=>p.u===u);
  if (ex && Date.now()<ex.exp) return { ok:false, r:'pending', exp:ex.exp };
  roles.pending = roles.pending.filter(p=>p.u!==u);
  roles.pending.push({ u, by, at:Date.now(), exp:Date.now()+PEND_TTL });
  roles_save(); return { ok:true };
};
const confirmMod = u => {
  const i = roles.pending.findIndex(p=>p.u===u);
  if (i<0) return { ok:false, r:roles.mods.includes(u)?'confirmed':'not_pending' };
  if (Date.now() > roles.pending[i].exp) { roles.pending.splice(i,1); roles_save(); return { ok:false, r:'expired' }; }
  const by = roles.pending[i].by; roles.pending.splice(i,1);
  if (!roles.mods.includes(u)) roles.mods.push(u);
  roles_save(); return { ok:true, u, by };
};
const getPending   = () => roles.pending.filter(p=>Date.now()<p.exp).sort((a,b)=>a.exp-b.exp);
const goOnDuty     = u => { if(isMod(u)){modsOnDuty.add(u);return'mod';} if(isDev(u)){devsOnDuty.add(u);return'dev';} return null; };
const goOffDuty    = u => { const was=modsOnDuty.has(u)?'mod':devsOnDuty.has(u)?'dev':null; modsOnDuty.delete(u); devsOnDuty.delete(u); return was; };
const isOnDuty     = u => modsOnDuty.has(u)||devsOnDuty.has(u);
const modBoost     = () => modsOnDuty.size > 0 ? C.get('mod_onduty_boost') : 0;
const getBudget    = u => { const t=new Date().toISOString().slice(0,10); let b=budgets.get(u); if(!b||b.date!==t){b={date:t,free:0,paid:0};budgets.set(u,b);} return b; };
const freeBudget   = u => isDev(u) ? C.get('airdrop_dev_budget') : C.get('airdrop_mod_budget');
const freeLeft     = u => Math.max(0, freeBudget(u) - getBudget(u).free);
const useBudget    = (u, amt, type) => { getBudget(u)[type] += amt; };

setInterval(() => {
  const exp = roles.pending.filter(p=>Date.now()>=p.exp);
  if (!exp.length) return;
  roles.pending = roles.pending.filter(p=>Date.now()<p.exp);
  exp.forEach(p => { modsOnDuty.delete(p.u); say(`⚠️ @${p.u}'s provisional Mod role expired.`); });
  roles_save();
}, 3600000);

// ═══════════════════════════════════════════════════════════════════════════════
// INLINED: LOTTERY
// ═══════════════════════════════════════════════════════════════════════════════
const lottery    = lotteryStore.data;
if (!lottery.tickets)  lottery.tickets  = {};
if (!lottery.lastDraw) lottery.lastDraw  = null;

const setTicket = (u, t) => {
  if (!t || !/^[1-4]{4}$/.test(t)) return { ok:false, error:'Ticket must be exactly 4 digits, each 1-4 (e.g. 1342)' };
  lottery.tickets[u] = t; lotteryStore.save(); return { ok:true, ticket:t };
};
const fmtTicket = t => t ? t.split('').join('-') : 'none';
const LOTTO_TIERS = {
  1: { name:'Common',  emoji:'🟢', prize:100    },
  2: { name:'Rare',    emoji:'🔵', prize:500    },
  3: { name:'Epic',    emoji:'🟣', prize:2000   },
  4: { name:'Jackpot', emoji:'🌟', prize:10000  },
};

const runLottery = () => {
  const drawn = Array.from({length:4}, ()=>Math.floor(Math.random()*4)+1).join('');
  const byTier = { 1:[], 2:[], 3:[], 4:[] };

  for (const [u, t] of Object.entries(lottery.tickets)) {
    let matches = 0;
    for (let i = 0; i < 4; i++) if (t[i] === drawn[i]) matches++;
    if (matches < 1) continue;
    const tier  = LOTTO_TIERS[matches];
    const prize = tier.prize;
    addBalance(u, prize);
    byTier[matches].push({ user:u, ticket:t, matches, prize, tier:tier.name });
  }

  const allWinners = [...byTier[4],...byTier[3],...byTier[2],...byTier[1]];
  lottery.lastDraw = { drawn, date:today(), winners:allWinners, byTier };
  lotteryStore.save();

  say(`🎰 Daily Lottery draw! Winning numbers: ${fmtTicket(drawn)}`);
  if (!allWinners.length) {
    say(`No winners tonight — buy your ticket with !lottoupdate 1234 🍀`);
  } else {
    // Announce each tier that had winners
    for (const m of [4,3,2,1]) {
      const tier = LOTTO_TIERS[m];
      const ws   = byTier[m];
      if (!ws.length) continue;
      say(`${tier.emoji} ${tier.name} (${m}/4): ${ws.map(w=>`@${w.user} +${fmtN(tier.prize)}🍫`).join(' · ')}`);
    }
  }

  broadcast({ type:'lottery:draw', drawn, winners:allWinners, byTier });
  return { drawn, winners:allWinners, byTier };
};
// Schedule daily draw at midnight UTC
const msToMidnight = () => { const n=new Date(),m=new Date(Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),n.getUTCDate()+1)); return m-n; };
const scheduleLottery = () => setTimeout(() => { runLottery(); setInterval(runLottery, 86400000); }, msToMidnight());
scheduleLottery();
console.log(`[Lottery] ${Object.keys(lottery.tickets).length} tickets | Next draw: ${Math.round(msToMidnight()/3600000)}h`);

// ═══════════════════════════════════════════════════════════════════════════════
// MUSIC IPC (reads musicPlayer state file)
// ═══════════════════════════════════════════════════════════════════════════════
// ── Music vote tracker ───────────────────────────────────────────────────────
const musicVotes = { on: new Map(), off: new Map() }; // user → timestamp
const VOTE_WINDOW  = 10 * 60 * 1000; // 10 minutes
const VOTE_NEEDED  = 3;

function recordMusicVote(user, direction) {
  const now = Date.now();
  const map = musicVotes[direction];
  const opp = musicVotes[direction === 'on' ? 'off' : 'on'];

  // Clear expired votes
  for (const [u, ts] of map) if (now - ts > VOTE_WINDOW) map.delete(u);
  for (const [u, ts] of opp) if (now - ts > VOTE_WINDOW) opp.delete(u);

  map.set(user, now); // one vote per user (overwrites their previous)

  if (map.size >= VOTE_NEEDED) {
    map.clear(); opp.clear();
    return true; // threshold reached
  }
  return false;
}

const MUSIC_CTRL  = '/tmp/choctotv_music_ctrl.json';
const MUSIC_STATE = '/tmp/choctotv_music_state.json';
const music_send  = (cmd, val) => { try { fs.writeFileSync(MUSIC_CTRL, JSON.stringify({cmd,val})); } catch {} };
const music_state = () => { try { return JSON.parse(fs.readFileSync(MUSIC_STATE,'utf8')); } catch { return null; } };
const music_isRunning = () => { const s = music_state(); return s !== null; };
let _musicProc = null;
const music_start = () => {
  if (music_isRunning()) return false; // already running
  const { spawn: _spawn } = require('child_process');
  _musicProc = _spawn(process.execPath, [path.join(__dirname, 'music.js')],
    { stdio:['ignore','pipe','pipe'], detached:false });
  _musicProc.stdout.on('data', d => process.stdout.write('[Music] ' + d));
  _musicProc.stderr.on('data', d => process.stderr.write('[Music] ' + d));
  _musicProc.on('exit', () => { _musicProc = null; });
  console.log('[Music] Started by !music command');
  return true;
};

// ═══════════════════════════════════════════════════════════════════════════════
// WEBSOCKET + EXPRESS
// ═══════════════════════════════════════════════════════════════════════════════
const wss = new WebSocketServer({ port:WS_PORT });
wss.on('listening', () => console.log(`[WS] :${WS_PORT}`));
wss.on('connection', ws => {
  ws.send(JSON.stringify({ type:'coins_update', coins:getCoins() }));
  ws.on('error', ()=>{});
});

const broadcast = payload => {
  const m = JSON.stringify(payload); let n = 0;
  wss.clients.forEach(c => { if (c.readyState === 1) { c.send(m); n++; } });
  return n;
};

const app = express();
app.use(express.json());
app.use(express.static(OVL_DIR));
app.get('/coins', (_, res) => res.json(getCoins()));
app.get('*', (_, res) => res.sendFile(path.join(OVL_DIR, 'index.html')));
app.listen(OVL_PORT, () => console.log(`[Overlay] :${OVL_PORT} → ${OVL_DIR}`));

const api = express();
api.use(express.json());

// ═══════════════════════════════════════════════════════════════════════════════
// TWITCH CHAT
// ═══════════════════════════════════════════════════════════════════════════════
const GAME_CMDS = new Set(['toss','throw','dig','walk','fish']);
const KNOWN_CMDS = new Set([...GAME_CMDS,'battle','balance','inventory','inv','cashout','convertchocto','oldwallet','addoldwallet','gauntlet',
  'vendsticks','vendballs','vendmoons','moonvend','forgeballs','forgemoons',
  'ticket','lottoupdate','top','weather','autopilot','settings','lurk','lick',
  'gbm','goodballmoon','song','skip','volume','music','config','update',
  'addcoin','removecoin','purge','roles','mod','unmod','dev','undev','confirm',
  'onduty','offduty','airdrop','hotfix','save']);
const CONJ = { tosses:'toss',tossing:'toss',tossed:'toss',throws:'throw',throwing:'throw',threw:'throw',thrown:'throw',digs:'dig',digging:'dig',dug:'dig',walks:'walk',walking:'walk',walked:'walk',fishes:'fish',fishing:'fish',fished:'fish',fishin:'fish',inv:'inventory',moonvend:'vendmoons' };
const NL_RULES = [
  { cmd:'toss',    re:/\b(toss(?:es|ing|ed)?)\b/i },
  { cmd:'throw',   re:/\b(throw(?:s|ing)?|threw|thrown)\b/i },
  { cmd:'dig',     re:/\b(dig(?:s|ging)?|dug)\b/i },
  { cmd:'walk',    re:/\b(walk(?:s|ing|ed)?)\b/i },
  { cmd:'fish',    re:/\b(fish(?:es|ing|ed)?|fishin)\b/i },
  { cmd:'battle',  re:/\b(battle(?:s|d)?|fight(?:s|ing)?|fought)\b/i },
  { cmd:'lurk',    re:/\b(lurk(?:ing)?)\b/i },
  { cmd:'lick',    re:/\b(lick(?:s|ing|ed)?)\b/i },
  { cmd:'balance', re:/\b(balance|my\s+balance|how\s+many\s+chocto(?:bits)?)\b/i },
];

let _client = null;
const _say  = [];

function say(msg) {
  if (!_client || !CHANNEL) return;
  _client.say(`#${CHANNEL}`, msg).catch(e => console.error('[Chat] say error:', e.message));
}

function startChat() {
  if (!CHANNEL) { console.warn('[Chat] TWITCH_CHANNEL not set'); return; }
  if (!OAUTH_TOKEN || OAUTH_TOKEN === 'oauth:') { console.warn('[Chat] No OAuth token — read-only mode'); }

  const opts = {
    options: { debug: true },
    connection: { reconnect:true, secure:true, maxReconnectAttempts:Infinity },
    channels: [`#${CHANNEL}`],
  };

  if (BOT_NAME && OAUTH_TOKEN && OAUTH_TOKEN !== 'oauth:') {
    opts.identity = { username:BOT_NAME, password:OAUTH_TOKEN };
    console.log(`[Chat] Authenticating as ${BOT_NAME}`);
  } else {
    console.warn('[Chat] No credentials — commands will not work. Run: node setup.js');
  }

  _client = new tmi.Client(opts);

  _client.on('message', async (_ch, tags, message, self) => {
    if (self) return;
    const text = (message || '').trim();
    if (!text) return;

    const user  = (tags['display-name'] || tags.username || 'anon').toLowerCase();
    const isMod_ = !!(tags.mod || tags['user-type']==='mod' || tags.badges?.broadcaster || tags.badges?.moderator || user === CHANNEL);
    const isSub  = !!tags.subscriber;

    lurk_touch(user);
    markActive(user);

    // ── Natural language checks (music vote + gauntlet) ────────────────────────
    const msgLower = text.toLowerCase();
    const tLower   = msgLower;

    // Music vote — 3 unique viewers in 10 min toggles music
    if (!isMod_) {
      const voteOff = /music\s+off|turn\s+off\s+(?:the\s+)?music|stop\s+(?:the\s+)?music/.test(tLower);
      const voteOn  = /music\s+on|turn\s+(?:the\s+)?music\s+on|start\s+(?:the\s+)?music/.test(tLower);
      if (voteOff || voteOn) {
        const dir       = voteOff ? 'off' : 'on';
        const triggered = recordMusicVote(user, dir);
        const count     = musicVotes[dir].size;
        if (triggered) {
          music_send(dir);
          say(`🗳️ Vote passed! Music turned ${dir} by community vote (${VOTE_NEEDED}/${VOTE_NEEDED}) 🎵`);
          broadcast({ type:'music_vote', direction:dir, passed:true });
        } else {
          say(`🗳️ @${user} voted music ${dir} (${count}/${VOTE_NEEDED} votes — ${VOTE_NEEDED - count} more needed in 10 min)`);
          broadcast({ type:'music_vote', direction:dir, count, needed:VOTE_NEEDED });
        }
        return;
      }
    }

    // Gauntlet NL trigger — only if not starting with !
    if (!text.startsWith('!')) {
      const wantsGauntlet = /i\s+(want|wanna|wish)\s+to\s+run\s+(the\s+)?gauntlet/i.test(text);
      if (wantsGauntlet) {
        if (onCooldown(user, isMod_, isSub)) return;
        handleCommand('gauntlet', user, [], isMod_).catch(()=>{});
        return;
      }
    }

    // ── ! commands ────────────────────────────────────────────────────────────
    if (text.startsWith('!')) {
      const parts = text.slice(1).trim().split(/\s+/);
      const raw   = parts[0].toLowerCase();
      const cmd   = CONJ[raw] || raw;
      const args  = parts.slice(1);
      if (!KNOWN_CMDS.has(cmd)) return;
      if (['update','addcoin','removecoin','hotfix','config'].includes(cmd) && !isMod_) return;
        if (onCooldown(user, isMod_, isSub)) return;
      console.log(`[Chat] !${cmd}${args.length?' '+args.join(' '):''} ← @${user}`);
      try { await handleCommand(cmd, user, args, isMod_); } catch(e) { console.error('[Chat] Error:', e.message); }
      return;
    }

    // ── Natural language ──────────────────────────────────────────────────────
    for (const rule of NL_RULES) {
      if (!text.match(rule.re)) continue;
      if (onCooldown(user, isMod_, isSub)) return;
      const args = [];
      console.log(`[Chat] NL:${rule.cmd} ← @${user} "${text.slice(0,60)}"`);
      try { await handleCommand(rule.cmd, user, args, isMod_); } catch(e) { console.error('[Chat] Error:', e.message); }
      return;
    }
  });

  _client.on('connected',    (h, p)  => console.log(`[Chat] Connected → ${h}:${p} | #${CHANNEL}`));
  _client.on('disconnected', reason  => {
    console.warn('[Chat] Disconnected:', reason);
    if (reason && /no response|login|auth|improperly/i.test(reason)) {
      console.error('[Chat] ⚠ Token rejected. Run: node setup.js');
    }
  });
  _client.on('reconnect',    ()      => console.log('[Chat] Reconnecting...'));

  _client.connect().catch(e => console.error('[Chat] Connect failed:', e.message || e));
}

// ═══════════════════════════════════════════════════════════════════════════════
// AUTOPILOT
// ═══════════════════════════════════════════════════════════════════════════════
let autopilot = null;
const startAutopilot = () => {
  if (autopilot) return;
  autopilot = setInterval(() => {
    const g = [...GAME_CMDS][Math.floor(Math.random()*GAME_CMDS.size)];
    handleCommand(g, 'AutoPilot', [], true).catch(()=>{});
  }, C.get('autopilot_sec') * 1000);
};
const stopAutopilot = () => { if (autopilot) { clearInterval(autopilot); autopilot = null; } };

// ═══════════════════════════════════════════════════════════════════════════════
// MAIN COMMAND HANDLER
// ═══════════════════════════════════════════════════════════════════════════════
const animating = new Set();

async function handleCommand(cmd, user, args=[], isModArg=false) {
  const isStreamer = user.toLowerCase() === CHANNEL;
  const isMod_    = isModArg || isStreamer || isMod(user.toLowerCase());
  const u         = user.toLowerCase();

  // ── Game commands ─────────────────────────────────────────────────────────
  if (GAME_CMDS.has(cmd) || cmd === 'lurk_tick') {
    const game = cmd === 'lurk_tick' ? [...GAME_CMDS][Math.floor(Math.random()*GAME_CMDS.size)] : cmd;
    if (cmd !== 'lurk_tick' && isRepeat(u, game)) { say(`❌ @${user} can't use !${game} twice in a row — mix it up!`); return { ok:false }; }
    if (animating.has(`${u}:${game}`)) return { ok:false };

    markActive(u);
    const pupId  = assignPup();
    const pup    = getPupName(pupId);
    const rarity = getPupRarity(pupId);
    const bonus  = getPupBonus(pup, game);
    const isLurk = lurk_active(u);
    const lurkM  = isLurk ? C.get('lurk_reward_mult') : 1;
    const modM   = 1 + modBoost();
    const amt    = Math.round(calcReward(game) * bonus.mult * lurkM * modM);
    const drops  = rollDrops();
    const fishR  = undefined; // fish catch determined by catchPup() below
    const caught = game === 'fish' ? catchPup(pupId, rarity) : null;

    addBalance(u, amt);
    if (Object.keys(drops).length) addItems(u, drops);
    const bal     = getBalance(u);
    const dropStr = Object.entries(drops).filter(([,n])=>n>0).map(([t,n])=>`${n}${ICONS[t]}`).join(' ');
    const bonStr  = bonus.bonuses.length===2?' ✨ MAX BONUS! +20%':bonus.bonuses.length===1?' ⭐ Bonus +10%':'';

    animating.add(`${u}:${game}`);
    broadcast({ type:'game', command:game, user, pupId, reward:amt, balance:bal, rarity:caught?.catchRarity||rarity, drops, pupName:pup, pupRarity:rarity, favGame:bonus.favGame, favWeather:bonus.favWeather, catchId:caught?.catchId, catchName:caught?.catchName, catchRarity:caught?.catchRarity });

    const startMsgs = {
      toss:  pup ? `🎯 @${user} tossed a stick! ${pup} (${rarity}) ran after it!`  : `🎯 @${user} tossed a stick!`,
      throw: pup ? `🎾 @${user} threw a ball! ${pup} (${rarity}) chased it!`       : `🎾 @${user} threw a ball!`,
      dig:   pup ? `⛏️ @${user} sent ${pup} (${rarity}) digging!`                   : `⛏️ @${user} is digging!`,
      walk:  pup ? `🐾 @${user} sent ${pup} (${rarity}) for a walk!`                : `🐾 @${user} is walking!`,
      fish:  pup ? `🎣 @${user} & ${pup} (${rarity}) cast a line...`              : `🎣 @${user} cast a line...`,
    };
    if (cmd !== 'lurk_tick') say(startMsgs[game] || `@${user} played ${game}!`);

    const delay = 5000 + ({toss:1800,throw:2000,dig:1500,walk:0,fish:2300}[game]||2000);
    setTimeout(() => {
      const endMsgs = {
        toss:  `🎯 Done! +${fmtN(amt)}${ICONS.chocto}${dropStr?' + '+dropStr:''}${bonStr}`,
        throw: `🎾 Fetched! +${fmtN(amt)}${ICONS.chocto}${dropStr?' + '+dropStr:''}${bonStr}`,
        dig:   `⛏️ Done! +${fmtN(amt)}${ICONS.chocto}${dropStr?' + '+dropStr:''}${bonStr}`,
        fish:  caught ? `🎣 Caught a ${caught.catchRarity} Choctonaut: ${caught.catchName}! +${fmtN(amt)}${ICONS.chocto}${dropStr?' + '+dropStr:''}${bonStr}` : `🎣 @${user} reeled something in! +${fmtN(amt)}${ICONS.chocto}${bonStr}`,
      };
      if (cmd !== 'lurk_tick' && endMsgs[game]) say(`@${user} ${endMsgs[game]} (bal: ${fmtN(bal)})`);
      animating.delete(`${u}:${game}`);
    }, delay);
    return { ok:true, command:game, user, reward:amt, balance:bal, drops };
  }

  // ── Gauntlet ─────────────────────────────────────────────────────────────
  if (cmd === 'gauntlet') {
    if (!isStreamer && !gauntlet_canRun(u)) {
      say(`❌ @${user} you've already run the Gauntlet today — come back tomorrow!`);
      return { ok:false };
    }
    if (!isStreamer) gauntlet_markUsed(u); // streamer unlimited runs
    broadcast({ type:'gauntlet_request', user, pupId:assignPup() });
    say(`⚔️ @${user} is calling for the GAUNTLET! Viewers have 1 minute to join with !battle — or face it alone!`);
    return { ok:true };
  }

  // ── Battle ────────────────────────────────────────────────────────────────
  if (cmd === 'battle') {
    broadcast({ type:'battle', user, pupId:assignPup() });
    // Queue feedback — overlay manages the actual queue,
    // this is just a chat acknowledgement
    say(`⚔️ @${user} joined Puppy Wars!`);
    return { ok:true };
  }

  // ── Balance ───────────────────────────────────────────────────────────────
  if (cmd === 'balance') { const b=getBalance(u); say(`${ICONS.chocto} @${user}: ${fmtN(b)} Choctobits`); broadcast({ type:'balance', user, balance:b }); return { ok:true, balance:b }; }

  // ── Inventory ─────────────────────────────────────────────────────────────
  if (cmd === 'inventory' || cmd === 'inv') {
    const i=getItems(u), b=getBalance(u);
    say(`🎒 @${user}: ${fmtN(b)}${ICONS.chocto} · ${fmtN(i.sticks)}${ICONS.sticks} · ${fmtN(i.balls)}${ICONS.balls} · ${fmtN(i.moons)}${ICONS.moons}`);
    return { ok:true, balance:b, ...i };
  }

  // ── Vend ──────────────────────────────────────────────────────────────────
  if (cmd === 'vendsticks'||cmd === 'vendballs'||cmd === 'vendmoons'||cmd === 'moonvend') {
    const item = cmd==='vendsticks'?'sticks':cmd==='vendballs'?'balls':'moons';
    const rate = { sticks:C.get('vend_sticks_rate'), balls:C.get('vend_balls_rate'), moons:C.get('vend_moons_rate') }[item];
    const mn=C.get('vend_min'), mx=C.get('vend_max');
    const amt=parseInt(args[0]);
    if (isNaN(amt)||amt<mn||amt>mx) { say(`❌ @${user} usage: !vend${item} ${mn}-${mx}`); return { ok:false }; }
    const inv=getItems(u);
    if ((inv[item]||0)<amt) { say(`❌ @${user} only ${fmtN(inv[item]||0)}${ICONS[item]}`); return { ok:false }; }
    const r=spendItems(u,{[item]:amt});
    if (!r.ok) { say(`❌ @${user} ${r.error}`); return { ok:false }; }
    const earns=amt*rate; addBalance(u,earns);
    say(`${ICONS[item]} @${user} sold ${fmtN(amt)} → +${fmtN(earns)}${ICONS.chocto} (bal: ${fmtN(getBalance(u))})`);
    broadcast({ type:'vend', item, user, amount:amt, earns });
    return { ok:true };
  }

  // ── Forge ─────────────────────────────────────────────────────────────────
  if (cmd === 'forgeballs') {
    const inv=getItems(u), cost=C.get('forge_balls_cost'), batches=Math.floor((inv.sticks||0)/cost);
    if (!batches) { say(`❌ @${user} need ${cost}${ICONS.sticks} per ball. Have ${fmtN(inv.sticks||0)}.`); return { ok:false }; }
    spendItems(u,{sticks:batches*cost}); addItems(u,{balls:batches});
    say(`⚗️ @${user} forged ${fmtN(batches*cost)}${ICONS.sticks} → ${fmtN(batches)}${ICONS.balls}!`);
    return { ok:true };
  }
  if (cmd === 'forgemoons') {
    const inv=getItems(u), cost=C.get('forge_moons_cost'), batches=Math.floor((inv.balls||0)/cost);
    if (!batches) { say(`❌ @${user} need ${cost}${ICONS.balls} per moon. Have ${fmtN(inv.balls||0)}.`); return { ok:false }; }
    spendItems(u,{balls:batches*cost}); addItems(u,{moons:batches});
    say(`🌙 @${user} forged ${fmtN(batches*cost)}${ICONS.balls} → ${fmtN(batches)}${ICONS.moons}!`);
    return { ok:true };
  }

  // ── Cashout toggle (streamer only) ──────────────────────────────────────
  // ── !cashout — converts Choctobits to Choctopus at 1000:1 ─────────────────
  // Flow: user !cashout → app says "!Convert X Choctopus for @user"
  //       Firebot reads it, adds Choctopus to wallet, sends POST /cashout/confirm
  //       App receives 200 OK → deducts converted amount from balance
  if (cmd === 'cashout') {
    const bal        = getBalance(u);
    const choctopus  = Math.floor(bal / 1000);
    const remainder  = bal % 1000;

    if (choctopus < 1) {
      say(`❌ @${user} you need at least 1,000🍫 to cashout (you have ${fmtN(bal)}🍫)`);
      return { ok:false };
    }

    // Hold conversion in pending map (5 min expiry)
    pendingCashouts.set(u, { choctopus, deduct: choctopus * 1000, remainder, ts: Date.now() });

    // This exact message format is what Firebot listens for
    // Firebot parses: $arg1=amount $arg4=@user
    say(`!Convert ${choctopus} Choctopus for @${user}`);
    return { ok:true, user, choctopus, remainder };
  }

  // ── !oldwallet — user triggers Firebot to check their old balance ───────────
  if (cmd === 'oldwallet') {
    say(`🔍 Checking @${user}'s old Choctopus wallet... Firebot is on it!`);
    // Firebot listens for this message, looks up old balance,
    // then sends: !addoldwallet @username <amount>
    return { ok:true };
  }

  // ── !addoldwallet — hidden, Firebot sends this with old balance amount ────
  // Only callable by the bot account or streamer
  if (cmd === 'addoldwallet') {
    const callerIsBot     = user.toLowerCase() === BOT_NAME.toLowerCase();
    const callerIsAllowed = callerIsBot || isStreamer;
    if (!callerIsAllowed) return { ok:false };

    const target = (args[0] || '').replace(/^@/, '').toLowerCase();
    const amount = parseInt(args[1]);

    if (!target) { say(`❌ Usage: !addoldwallet @username <amount>`); return { ok:false }; }
    if (isNaN(amount) || amount <= 0) { say(`❌ Invalid amount`); return { ok:false }; }

    addBalance(target, amount);
    const newBal = getBalance(target);
    say(`✅ @${target}'s old wallet loaded! +${fmtN(amount)}🍫 added → new balance: ${fmtN(newBal)}🍫`);
    broadcast({ type:'balance', user:target, balance:newBal });
    return { ok:true, user:target, amount, balance:newBal };
  }

  // ── !top — leaderboard in chat ───────────────────────────────────────────────
  if (cmd === 'top') {
    const entries = Object.entries(balanceStore.data)
      .filter(([u]) => u !== CHANNEL)
      .sort(([,a],[,b]) => b - a)
      .slice(0, 5);
    if (!entries.length) { say(`🏆 No balances yet!`); return { ok:true }; }
    const medals = ['🥇','🥈','🥉','4️⃣','5️⃣'];
    const line = entries.map(([u,b],i) => `${medals[i]} @${u} ${fmtN(b)}`).join('  ·  ');
    say(`🏆 Top Choctobits: ${line}`);
    return { ok:true };
  }

  // ── Lurk ──────────────────────────────────────────────────────────────────
  if (cmd === 'lurk') { lurk_touch(u); const r=lurk_add(u); say(r.existing?`😴 @${user} extended lurk!`:`😴 @${user} entered lurk mode! (${C.get('lurk_reward_mult')*100}% earn rate) 🌙`); broadcast({type:'lurk_start',user}); return { ok:true }; }

  // ── Lick (chest) ──────────────────────────────────────────────────────────
  if (cmd === 'lick') { const r=await chest_lick(u); if(!r.popped) say(`👅 @${user} licked! -${r.clicks} | 🔒${r.lock} left`); return { ok:true }; }

  // ── GBM ───────────────────────────────────────────────────────────────────
  if (cmd === 'gbm' || cmd === 'goodballmoon') {
    if (!args[0]) { say(`🎮 @${user} use !GBM Good/Ball/Moon | Next round: ${Math.ceil((gbmNext-Date.now())/60000)}min`); return { ok:true }; }
    const r=gbm_pick(u,args[0]);
    if (!r.ok) { say(`❌ @${user} ${r.error}`); return { ok:false }; }
    say(`🎮 @${user} picked ${r.pick}!`);
    broadcast({ type:'gbm_pick', user, pick:r.pick });
    return { ok:true };
  }

  // ── Lottery ───────────────────────────────────────────────────────────────
  if (cmd === 'lottoupdate') { const r=setTicket(u,args[0]||''); if(!r.ok){say(`❌ @${user} ${r.error}`);return{ok:false};} say(`🎰 @${user} ticket: ${fmtTicket(r.ticket)}`); return { ok:true }; }
  if (cmd === 'ticket') { const t=lottery.tickets[u]; say(t?`🎰 @${user}: ${fmtTicket(t)}`:`🎰 @${user} no ticket! Use !lottoupdate 1342`); return { ok:true }; }

  // ── Weather ───────────────────────────────────────────────────────────────
  if (cmd === 'weather') { weather=WEATHERS[Math.floor(Math.random()*WEATHERS.length)]; broadcast({type:'weather',weather}); say(`${W_ICONS[weather]||'🌤️'} Weather: ${weather}!`); return { ok:true }; }

  // ── Autopilot ─────────────────────────────────────────────────────────────
  if (cmd === 'autopilot') {
    if (autopilot) { stopAutopilot(); broadcast({type:'autopilot',active:false}); say('🤖 Autopilot off'); }
    else { startAutopilot(); broadcast({type:'autopilot',active:true}); say(`🤖 Autopilot on — every ${C.get('autopilot_sec')}s`); }
    return { ok:true, autopilot:!!autopilot };
  }

  // ── Settings overlay ──────────────────────────────────────────────────────
  if (cmd === 'settings') { broadcast({type:'settings'}); return { ok:true }; }

  // ── Music ─────────────────────────────────────────────────────────────────
  if (cmd === 'song') { const s=music_state(); s?.track?say(`🎵 ${s.track.name} [${Math.floor((Date.now()-s.track.startedAt)/60000)}m]`):say(`🎵 No music playing`); return { ok:true }; }
  if (cmd === 'skip') { if(!isMod_){say(`❌ Mods only`);return{ok:false};} music_send('skip'); say(`⏭️ @${user} skipped`); return { ok:true }; }
  if (cmd === 'volume') { if(!isMod_){say(`❌ Mods only`);return{ok:false};} const v=parseInt(args[0]); if(isNaN(v)||v<0||v>100){say(`❌ !volume 0-100`);return{ok:false};} music_send('volume',v); C.set('music_volume',v); say(`🔊 Volume: ${v}%`); return { ok:true }; }
  if (cmd === 'music') {
    // Mods and streamer can also toggle — bypasses vote
    if (!isStreamer && !isMod_) { say(`❌ Streamer/Mod only — viewers can vote !music on/off`); return { ok:false }; }
    const sub = (args[0]||'').toLowerCase();
    const running = music_isRunning();

    if (sub === 'start' || (sub === 'on' && !running)) {
      if (music_start()) {
        setTimeout(() => { music_send('on'); }, 2000);
        say(`🎵 Music service started!`);
      } else {
        music_send('on');
        say(`🎵 Music on`);
      }
    } else if (sub === 'on') {
      music_send('on'); say(`🎵 Music on`);
    } else if (sub === 'off') {
      music_send('off'); say(`🔇 Music off`);
    } else if (sub === 'list') {
      const st = music_state();
      say(st?.trackCount ? `🎵 ${st.trackCount} track(s) loaded` : `🎵 No tracks found in ./music/`);
    } else {
      // No subcommand — show status
      const st = music_state();
      if (!running) {
        say(`🔇 Music not running — use !music start to launch it`);
      } else if (st?.track) {
        const el = Math.floor((Date.now()-st.track.startedAt)/60000);
        say(`🎵 Playing: ${st.track.name} [${el}m] | vol:${st.volume||50}% | !music off/on/skip`);
      } else {
        say(`🎵 Music ready | ${st?.trackCount||0} tracks | !music on to start`);
      }
    }
    return { ok:true };
  }

  // ── Roles ─────────────────────────────────────────────────────────────────
  if (cmd === 'mod'||cmd === 'unmod'||cmd === 'dev'||cmd === 'undev') {
    const target=(args[0]||'').replace(/^@/,'').toLowerCase();
    if (!target) { say(`ℹ️ !${cmd} @username`); return { ok:false }; }
    if (cmd==='mod') {
      if (isStreamer) { addMod(target); say(`🛡️ @${target} is now a confirmed Mod!`); }
      else if (isDev(u)) { const r=addPending(target,u); r.ok?say(`🛡️ @${target} provisional Mod — streamer !confirm within 7 days`):say(`❌ ${r.r==='confirmed'?'Already confirmed':r.r==='pending'?'Already pending':'Error'}`); }
      else { say(`❌ Only streamer/Dev can assign Mod`); return { ok:false }; }
    } else if (cmd==='unmod') { if(!isStreamer){say(`❌ Streamer only`);return{ok:false};} remMod(target); say(`🛡️ @${target} Mod removed`); }
    else if (cmd==='dev') { if(!isStreamer){say(`❌ Streamer only`);return{ok:false};} addDev(target); say(`🔧 @${target} is now a Dev!`); }
    else if (cmd==='undev') { if(!isStreamer){say(`❌ Streamer only`);return{ok:false};} remDev(target); say(`🔧 @${target} Dev removed`); }
    broadcast({ type:'roles_update', mods:roles.mods, devs:roles.devs });
    return { ok:true };
  }
  if (cmd === 'confirm') {
    if (!isStreamer) { say(`❌ Streamer only`); return { ok:false }; }
    const target=(args[0]||'').replace(/^@/,'').toLowerCase();
    if (!target) { const p=getPending(); p.length?say(`⏳ Pending: ${p.map(x=>`@${x.u}(${Math.ceil((x.exp-Date.now())/86400000)}d)`).join(' ')}`):say(`✅ No pending`); return { ok:true }; }
    const r=confirmMod(target); r.ok?say(`✅ @${target} confirmed as Mod!`):say(`❌ ${r.r}`); return { ok:r.ok };
  }
  if (cmd === 'roles') { say(`🛡️ Mods: ${roles.mods.join(',')||'none'} | Duty: ${[...modsOnDuty].join(',')||'none'}`); say(`🔧 Devs: ${roles.devs.join(',')||'none'} | Duty: ${[...devsOnDuty].join(',')||'none'}`); return { ok:true }; }
  if (cmd === 'onduty') { const role=goOnDuty(u); if(!role){say(`❌ @${user} no Mod/Dev role`);return{ok:false};} role==='mod'?say(`🛡️ @${user} ON DUTY! +${Math.round(C.get('mod_onduty_boost')*100)}% rewards! Budget: ${fmtN(freeLeft(u))}🍫`):say(`🔧 @${user} ON DUTY! Airdrop budget: ${fmtN(freeLeft(u))}🍫`); broadcast({type:'onduty',user,role}); return { ok:true }; }
  if (cmd === 'offduty') { const was=goOffDuty(u); if(!was){say(`❌ Not on duty`);return{ok:false};} say(`👋 @${user} off duty`); broadcast({type:'offduty',user}); return { ok:true }; }

  // ── Airdrop ───────────────────────────────────────────────────────────────
  if (cmd === 'airdrop') {
    if (!canDrop(u)) { say(`❌ Mods/Devs only`); return { ok:false }; }
    if (!isOnDuty(u)) { say(`❌ @${user} use !onduty first`); return { ok:false }; }
    const amt=parseInt(args[0]), mn=C.get('airdrop_min'), mx=C.get('airdrop_max');
    if (isNaN(amt)||amt<mn) { say(`❌ Min ${fmtN(mn)}🍫`); return { ok:false }; }
    if (amt>mx) { say(`❌ Max ${fmtN(mx)}🍫`); return { ok:false }; }
    const fl=freeLeft(u);
    const win=C.get('airdrop_window_min')*60000, now=Date.now();
    const eligible=[...activeUsers.entries()].filter(([eu,ts])=>eu!==u&&now-ts<win).map(([eu])=>eu);
    if (!eligible.length) { say(`❌ No active users in last ${C.get('airdrop_window_min')} min`); return { ok:false }; }
    const share=Math.floor(amt/eligible.length); if(share<1){say(`❌ Amount too small to split`);return{ok:false};}
    const actual=share*eligible.length;
    let type;
    if (fl>=actual) { type='free'; }
    else if (fl>0&&fl<actual) { say(`❌ Only ${fmtN(fl)}🍫 free left. Try !airdrop ${fmtN(Math.floor(fl/eligible.length)*eligible.length)}`); return{ok:false}; }
    else if (isDev(u)) { if(getBalance(u)<actual){say(`❌ Not enough balance`);return{ok:false};} subBalance(u,actual); type='paid'; }
    else { say(`❌ Daily budget exhausted. Resets midnight UTC.`); return { ok:false }; }
    useBudget(u,actual,type);
    eligible.forEach(eu=>addBalance(eu,share));
    const icon=isMod(u)?'🛡️':'🔧', fund=type==='free'?'🆓':'💸';
    say(`🪂 AIRDROP! ${icon} @${user} ${fund} — ${fmtN(actual)}🍫 to ${eligible.length} players! +${fmtN(share)}🍫 each 🎉`);
    broadcast({type:'airdrop',dropper:user,amount:actual,share,recipients:eligible.length});
    if(freeLeft(u)>0)say(`ℹ️ @${user} free budget left: ${fmtN(freeLeft(u))}🍫`);
    return { ok:true };
  }

  // ── Config (streamer only) ────────────────────────────────────────────────
  if (cmd === 'config') {
    if (!isStreamer) { say(`❌ Streamer only`); return { ok:false }; }
    const key=args[0]?.toLowerCase(), val=args[1];
    if (!key||key==='list') { say(`⚙️ ${Object.keys(CONFIG_DEFAULTS).join(' · ')}`); return { ok:true }; }
    if (!val) { say(`⚙️ ${key}=${C.get(key)}`); return { ok:true }; }
    const r=C.set(key,val); if(!r.ok){say(`❌ ${r.error}`);return{ok:false};}
    if (key==='autopilot_sec'&&autopilot){stopAutopilot();startAutopilot();}
    if (key==='gbm_round_min'){gbm_schedule();}
    say(`✅ @${user} ${key}: ${r.prev} → ${r.value}`);
    broadcast({type:'settings_update',key,value:r.value});
    return { ok:true };
  }

  // ── !update (token/channel refresh) ──────────────────────────────────────
  if (cmd === 'update') {
    if (!isStreamer) { say(`❌ Streamer only`); return { ok:false }; }
    const [sub, ...rest] = args;
    if (!sub) { say(`ℹ️ !update oauth <token> | !update channel <name>`); return { ok:false }; }
    if (sub==='oauth') {
      const tok=rest[0]; if(!tok){say(`❌ !update oauth oauth:xxx`);return{ok:false};}
      process.env.TWITCH_OAUTH_TOKEN=tok; writeEnvKey('TWITCH_OAUTH_TOKEN',tok);
      say(`✅ Token updated — reconnecting...`);
      if (_client) { _client.disconnect().catch(()=>{}).finally(()=>{setTimeout(startChat,1000);}); _client=null; }
      else startChat();
      return { ok:true };
    }
    if (sub==='channel') {
      const ch=(rest[0]||'').toLowerCase(); if(!ch){say(`❌ !update channel name`);return{ok:false};}
      writeEnvKey('TWITCH_CHANNEL',ch); say(`✅ Channel updated. Restart to apply.`); return { ok:true };
    }
    return { ok:false };
  }

  // ── Coins ─────────────────────────────────────────────────────────────────
  if (cmd==='addcoin')    { const r=addCoin(args[0],args[1]); if(!r.ok){say(`❌ ${r.error}`);return{ok:false};} broadcast({type:'coins_update',coins:getCoins()}); say(`✅ Added ${r.coin.sym}`); return{ok:true}; }
  if (cmd==='removecoin') { const r=removeCoin(args[0]); if(!r.ok){say(`❌ ${r.error}`);return{ok:false};} broadcast({type:'coins_update',coins:getCoins()}); say(`✅ Removed ${r.sym}`); return{ok:true}; }

  // ── Misc ──────────────────────────────────────────────────────────────────
  if (cmd==='save') { broadcast({type:'save_choctonaut',user}); say(`🦸 @${user} is saving the pup!`); return{ok:true}; }
  if (cmd==='hotfix') { broadcast({type:'shutdown'}); say(`🔧 Hotfix by @${user} — restarting...`); setTimeout(()=>process.exit(0),2000); return{ok:true}; }

  return { ok:false, error:`Unknown command: ${cmd}` };
}

// ═══════════════════════════════════════════════════════════════════════════════
// REST API
// ═══════════════════════════════════════════════════════════════════════════════
api.post('/command',      async (req,res) => { try{res.json(await handleCommand(req.body?.command||'',req.body?.user||CHANNEL,req.body?.args||[],true));}catch(e){res.status(500).json({error:e.message});} });
api.get ('/balance/:u',   (req,res) => res.json({ user:req.params.u, balance:getBalance(req.params.u) }));
api.get ('/balances',     (_,res) => res.json(Object.fromEntries(Object.entries(balanceStore.data).sort(([,a],[,b])=>b-a))));
api.get ('/leaderboard',  (_,res) => res.json(Object.entries(balanceStore.data).filter(([u])=>u!==CHANNEL).sort(([,a],[,b])=>b-a).slice(0,10).map(([u,b],i)=>({rank:i+1,user:u,balance:b}))));
api.get ('/items/:u',     (req,res) => res.json(getItems(req.params.u)));
api.get ('/coins',        (_,res) => res.json(getCoins()));
api.post('/coins/add',    (req,res) => { const r=addCoin(req.body?.sym,req.body?.id); if(r.ok)broadcast({type:'coins_update',coins:getCoins()}); res.json(r); });
api.post('/coins/remove', (req,res) => { const r=removeCoin(req.body?.sym); if(r.ok)broadcast({type:'coins_update',coins:getCoins()}); res.json(r); });
api.get ('/config',       (_,res) => res.json(C.all()));
api.post('/config',       (req,res) => res.json(C.set(req.body?.key,req.body?.value)));
api.post('/broadcast',    (req,res) => res.json({ ok:true, clients:broadcast(req.body) }));
api.post('/lottery/draw', (_,res) => res.json(runLottery()));
api.get('/lottery/today', (_,res) => {
  const d = lottery.lastDraw;
  const isToday = d && d.date === today();
  const bt = isToday ? d.byTier : null;
  res.json({
    drawn:      isToday ? d.drawn : null,
    display:    isToday ? d.drawn.split('').join('-') : null,
    date:       isToday ? d.date : null,
    winners:    isToday ? d.winners : [],
    byTier:     bt,
    jackpot:    bt?.[4]?.length || 0,
    epic:       bt?.[3]?.length || 0,
    rare:       bt?.[2]?.length || 0,
    common:     bt?.[1]?.length || 0,
    ticketCount: Object.keys(lottery.tickets).length,
  });
});
api.post('/addbalance', (req,res) => {
  const { user, amount } = req.body || {};
  if (!user || !amount || isNaN(parseInt(amount))) return res.json({ ok:false });
  addBalance(user.toLowerCase(), parseInt(amount));
  res.json({ ok:true, user, amount:parseInt(amount), balance:getBalance(user.toLowerCase()) });
});
api.post('/gauntlet/record', (req,res) => {
  const { user, wins, total } = req.body || {};
  if (!user) return res.json({ ok:false });
  const isStreamerRun = user.toLowerCase() === CHANNEL;
  let entry = { wins:parseInt(wins)||0, runs:1, total:parseInt(total)||0 };
  if (!isStreamerRun) {
    entry = gauntlet_record(user.toLowerCase(), parseInt(wins)||0, parseInt(total)||0);
  }
  const lb = gauntlet_leaderboard();
  broadcast({ type:'gauntlet_leaderboard', leaderboard:lb });
  // Shoutout in chat
  const rank = lb.findIndex(e => e.user === user.toLowerCase()) + 1;
  const pct  = Math.round((parseInt(wins)/Math.max(1,parseInt(total)))*100);
  if (parseInt(wins) === parseInt(total))
    say(`🏆 @${user} CONQUERED the entire Gauntlet — ${wins}/${total} pups defeated! ${entry.runs>1?`(Best: ${entry.wins} wins)`:''} Legendary run! 🐾`);
  else
    say(`⚔️ Gauntlet complete! @${user} defeated ${wins}/${total} pups (${pct}%)! ${rank<=3?`#${rank} on the leaderboard!`:``} Use !battle next time 👀`);
  res.json({ ok:true, entry, rank });
});
api.get('/gauntlet/leaderboard', (_,res) => res.json(gauntlet_leaderboard()));
// Firebot calls this after successfully adding Choctopus to user's wallet
// Returns 200 OK → app deducts the Choctobits from the game balance
api.post('/cashout/confirm', (req, res) => {
  const user = (req.body?.user || '').replace(/^@/,'').toLowerCase();
  if (!user) return res.status(400).json({ ok:false, error:'user required' });
  const pending = pendingCashouts.get(user);
  if (!pending) return res.status(404).json({ ok:false, error:'No pending cashout for ' + user });
  // Deduct converted coins, leave remainder
  const bal = getBalance(user);
  balanceStore.data[user] = Math.max(0, bal - pending.deduct);
  balanceStore.save();
  pendingCashouts.delete(user);
  console.log(`[Cashout] @${user} cashed out ${pending.choctopus} Choctopus — ${pending.deduct} coins deducted, ${pending.remainder} remain`);
  say(`✅ @${user} cashed out ${fmtN(pending.choctopus)} Choctopus! ${fmtN(pending.remainder)}🍫 remains in wallet.`);
  broadcast({ type:'cashout', user, choctopus:pending.choctopus, remainder:pending.remainder });
  res.json({ ok:true, user, choctopus:pending.choctopus, deducted:pending.deduct, remainder:pending.remainder });
});
api.get ('/health',       (_,res) => res.json({ ok:true, uptime:Math.floor(process.uptime()), ws:wss.clients.size, active:getActiveCount() }));
api.post('/shutdown',     (_,res) => { res.json({ok:true}); broadcast({type:'shutdown'}); setTimeout(()=>process.exit(0),500); });
api.listen(API_PORT, '127.0.0.1', () => console.log(`[API] :${API_PORT}`));

// ── Init ──────────────────────────────────────────────────────────────────────
console.log(`[App] ChoctoTV starting — channel: #${CHANNEL}`);
chest_new();
gbm_schedule();
startChat();

process.on('SIGTERM', () => { if(autopilot)stopAutopilot(); wss.close(()=>process.exit(0)); setTimeout(()=>process.exit(0),1500); });
process.on('SIGINT',  () => { if(autopilot)stopAutopilot(); wss.close(()=>process.exit(0)); setTimeout(()=>process.exit(0),1500); });

module.exports = { handleCommand, broadcast };
