#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  ChoctoTV — firststart.sh
#
#  One-time bootstrap. Called automatically by start.sh on first run.
#  Can also be called manually:
#    ./firststart.sh          → production (uses vault/secret.txt)
#    ./firststart.sh test     → test channel (uses vault/testzone.txt)
#
#  VAULT FOLDER (gitignored)
#  ─────────────────────────
#  Drop vault.zip in the project root. It extracts directly into vault/:
#
#    vault/secret.txt          ← production credentials
#    vault/testzone.txt        ← test channel credentials
#    vault/Secret.template.txt ← template for new installs
#    vault/ticker.txt          ← scrolling ticker content
#    vault/announcements.txt   ← pre-loaded announcements
#    vault/teller.json         ← live cashout config (optional)
#    vault/music/              ← background music tracks
#    vault/sprites/            ← pup sprite PNGs + sprites_meta.json
#    vault/billboard/main/     ← always-on billboard images
#    vault/billboard/ads/      ← subscriber ad images
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

GR='\033[0;32m'; YL='\033[0;33m'; RD='\033[0;31m'; CY='\033[0;36m'; NC='\033[0m'
ok()   { echo -e "${GR}  ✓${NC} $*"; }
info() { echo -e "${CY}  →${NC} $*"; }
warn() { echo -e "${YL}  ⚠${NC} $*"; }
die()  { echo -e "${RD}  ✗${NC} $*"; exit 1; }

echo ""
echo -e "${GR}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GR}  ChoctoTV — First-Run Bootstrap${NC}"
echo -e "${GR}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ── 1. Node.js version check ──────────────────────────────────────────────────
command -v node &>/dev/null || die "node not found — install Node.js >= 20 first"
NODE_VER=$(node --version | grep -oP '\d+' | head -1)
[ "$NODE_VER" -lt 20 ] && die "Node.js >= 20 required (found $(node --version))"
ok "Node.js $(node --version)"

# ── 2. npm install ────────────────────────────────────────────────────────────
cd "$DIR"
info "Installing dependencies..."
if [ ! -d node_modules ] || [ ! -f node_modules/.package-lock.json 2>/dev/null ]; then
  npm install --omit=dev 2>&1 \
    || npm install --omit=dev --legacy-peer-deps 2>&1 \
    || die "npm install failed"
  ok "npm install complete"
else
  ok "node_modules present — skipping"
fi

# native addon check
node -e "require('better-sqlite3')" 2>/dev/null && ok "better-sqlite3 OK" || {
  warn "better-sqlite3 needs rebuild..."
  npm rebuild better-sqlite3 || die "better-sqlite3 rebuild failed"
  ok "better-sqlite3 rebuilt"
}

# ── 3. Unzip vault.zip → vault/ ───────────────────────────────────────────────
VAULT="$DIR/vault"
mkdir -p "$VAULT"

VAULT_ZIP="$DIR/vault.zip"
if [ -f "$VAULT_ZIP" ]; then
  info "Extracting vault.zip → vault/ ..."
  unzip -o "$VAULT_ZIP" -d "$VAULT" -q
  ok "vault.zip extracted"
  # Ensure billboard subdirs exist
  mkdir -p "$VAULT/billboard/main" "$VAULT/billboard/ads" "$VAULT/billboard/review"
  mkdir -p "$VAULT/music" "$VAULT/sprites" "$VAULT/nobg"
else
  warn "vault.zip not found — skipping (place it in the project root)"
fi

# ── 4. Determine secret file ──────────────────────────────────────────────────
MODE="${1:-}"
SECRET_FILE=""

if [[ "$MODE" == "test" ]]; then
  for f in "$VAULT/testzone.txt" "$VAULT/Testzone.txt"; do
    [ -f "$f" ] && SECRET_FILE="$f" && break
  done
  [ -z "$SECRET_FILE" ] && die "vault/testzone.txt not found — check vault.zip contents"
  warn "TEST MODE — using $(basename "$SECRET_FILE")"
else
  for f in "$VAULT/secret.txt" "$VAULT/Secret.txt" "$VAULT/Secret(live).txt"; do
    [ -f "$f" ] && SECRET_FILE="$f" && break
  done
  [ -z "$SECRET_FILE" ] && die "vault/secret.txt not found — check vault.zip contents"
  ok "Using $(basename "$SECRET_FILE")"
fi

# ── 5. Generate vault/.env ────────────────────────────────────────────────────
info "Generating vault/.env from $(basename "$SECRET_FILE")..."
{
  echo "# Auto-generated by firststart.sh on $(date)"
  echo "# Source: $(basename "$SECRET_FILE")"
  echo ""
  while IFS= read -r line; do
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    line="${line%%  #*}"; line="${line%%	#*}"  # strip inline comments
    [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]] && echo "$line"
  done < "$SECRET_FILE"
} > "$VAULT/.env"
ok "vault/.env generated ($(grep -c '=' "$VAULT/.env") keys)"

# ── 6. Restore player data if DB is missing but vault backup exists ──────────
DB_FILE="$DIR/data/db/choctotv.db"
DB_BACKUP="$VAULT/persistence/choctotv.db"
if [ ! -f "$DB_FILE" ] && [ -f "$DB_BACKUP" ]; then
  info "Restoring player data from vault/persistence/..."
  mkdir -p "$(dirname "$DB_FILE")"
  cp "$DB_BACKUP" "$DB_FILE"
  # Restore cashouts if present
  CASH_BACKUP="$VAULT/persistence/cashouts.json"
  [ -f "$CASH_BACKUP" ] && { mkdir -p "$DIR/data/db"; cp "$CASH_BACKUP" "$DIR/data/db/cashouts.json"; }
  ok "Player data restored (balances, inventory, XP, wallets all intact)"
else
  [ -f "$DB_FILE" ] && ok "Existing player database found — keeping it"                     || ok "Fresh install — new database will be created on first start"
fi

# ── 7. Runtime data directories ───────────────────────────────────────────────
mkdir -p "$DIR/data/db" "$DIR/data/logs/sessions" "$DIR/data/.pids"
ok "data/ directories ready"

# ── 7. Mark bootstrap complete ───────────────────────────────────────────────
date -u +"%Y-%m-%dT%H:%M:%SZ" > "$DIR/.bootstrapped"
ok "Bootstrap complete"

echo ""
echo -e "${GR}━━━  Ready  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "  ${CY}./start.sh${NC}       production"
echo -e "  ${CY}./start.sh test${NC}  test channel (rydersbnc)"
echo ""
