'use strict';
/**
 * Teller — webhook dispatcher for !cashout and !vcode.
 *
 * Loads config from vault/cashout-webhook.json and vault/vcode-webhook.json
 * which are generated by start.sh from vault/.env on every boot.
 * Env vars (process.env.*) are used as fallback if the JSON files don't exist.
 *
 * Generated JSON format (both files same shape):
 *   { url, auth_type, auth_token, auth_user, auth_pass, guild_id, payload_format }
 */
const https = require('https');
const http  = require('http');
const path  = require('path');
const fs    = require('fs');

const VAULT = path.join(__dirname, '..', 'vault');

function loadConfig() {
  try {
    return JSON.parse(fs.readFileSync(path.join(VAULT, 'tipbot-webhook.json'), 'utf8'));
  } catch {
    return {
      url:        process.env.TIPBOT_WEBHOOK_URL       || '',
      auth_type:  process.env.TIPBOT_WEBHOOK_AUTH_TYPE  || '',
      auth_token: process.env.TIPBOT_WEBHOOK_AUTH_TOKEN || '',
      auth_user:  process.env.TIPBOT_WEBHOOK_AUTH_USER  || '',
      auth_pass:  process.env.TIPBOT_WEBHOOK_AUTH_PASS  || '',
      guild_id:   process.env.DISCORD_GUILD_ID          || '',
    };
  }
}

function buildAuth(cfg) {
  const type = (cfg.auth_type || '').toLowerCase();
  if (type === 'bearer' && cfg.auth_token)
    return { Authorization: `Bearer ${cfg.auth_token}` };
  if (type === 'basic' && cfg.auth_user) {
    const cred = `${cfg.auth_user}:${cfg.auth_pass || ''}`;
    return { Authorization: `Basic ${Buffer.from(cred).toString('base64')}` };
  }
  return {};
}

function post(url, payload, authHeaders, timeoutMs) {
  return new Promise((resolve, reject) => {
    const u    = new URL(url);
    const body = JSON.stringify(payload);
    const lib  = u.protocol === 'https:' ? https : http;
    const req  = lib.request(
      { hostname: u.hostname,
        port:     u.port || (u.protocol === 'https:' ? 443 : 80),
        path:     u.pathname + u.search,
        method:   'POST',
        headers:  { 'Content-Type': 'application/json',
                    'Content-Length': Buffer.byteLength(body),
                    ...authHeaders } },
      res => {
        let d = '';
        res.on('data', c => d += c);
        res.on('end', () => {
          let b = {};
          try { b = JSON.parse(d); } catch {}
          resolve({ status: res.statusCode, body: b });
        });
      }
    );
    req.setTimeout(timeoutMs, () => { req.destroy(); reject(new Error('tipbot timed out')); });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

/**
 * Send cashout payload to tipbot.
 * @param {{ user:string, user_id:string, amount:number }} args
 */
async function sendCashout({ user, user_id, amount }) {
  const cfg = loadConfig();
  if (!cfg.url) throw new Error('TIPBOT_WEBHOOK_URL not set — check secret.txt and restart');
  return post(cfg.url, {
    user, user_id, amount, guild_id: cfg.guild_id,
  }, buildAuth(cfg), 30000);
}

async function sendVcode({ code, user, user_id }) {
  const cfg = loadConfig();
  if (!cfg.url) throw new Error('TIPBOT_WEBHOOK_URL not set — check secret.txt and restart');
  return post(cfg.url, {
    verify: { code, user, user_id, guild_id: cfg.guild_id },
  }, buildAuth(cfg), 10000);
}

module.exports = { sendCashout, sendVcode };
